// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service4.proto

package grpc.service4;

public interface infoStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:infoString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 1 is a tag, not a content of the variable
   * </pre>
   *
   * <code>string firstInfoString = 1;</code>
   */
  java.lang.String getFirstInfoString();
  /**
   * <pre>
   * 1 is a tag, not a content of the variable
   * </pre>
   *
   * <code>string firstInfoString = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstInfoStringBytes();
}
