// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service6.proto

package grpc.service6;

public interface containsStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firststring = 1;</code>
   */
  java.lang.String getFirststring();
  /**
   * <code>string firststring = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirststringBytes();
}
