// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficManagement.proto

package grpc.newService;

public interface speedDoubleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speedDouble)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 1 is a tag, not a content of the variable
   * </pre>
   *
   * <code>double speed = 1;</code>
   */
  double getSpeed();
}
