// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficManagement.proto

package grpc.newService;

public final class SpeedControlServiceImp {
  private SpeedControlServiceImp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speedDouble_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speedDouble_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027trafficManagement.proto\"\034\n\013speedDouble" +
      "\022\r\n\005speed\030\001 \001(\0012D\n\023speedControlService\022-" +
      "\n\rGetOneVehicle\022\014.speedDouble\032\014.speedDou" +
      "ble\"\000B+\n\017grpc.newServiceB\026SpeedControlSe" +
      "rviceImpP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_speedDouble_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_speedDouble_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speedDouble_descriptor,
        new java.lang.String[] { "Speed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
